name: building, testing
run-name: ${{ github.actor }} is testing
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18.16.1 ]
    
    steps:
      - uses: actions/checkout@v2
      - name: Starting Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
        run: yarn
      - name: building production
        run: yarn build
        if: always()
      - name: building storybook
        run: yarn sb:static
        if: always()
      - name: testing snapshots
        run: yarn est:integ:sb:static
        if: always()
      - name: testing unit
        run: yarn test:ci
        if: always()
