name: building, testing
run-name: ${{ github.actor }} is testing
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18.16.1 ]
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: install modules
        run: yarn
        
      - name: building production
        run: CI=false yarn build
        if: always()
        
      - name: building storybook
        run: yarn build-storybook
        if: always()
        
      - name: testing snapshots
        run: yarn test:integ:sb:static
        if: always()
        
      - name: testing unit
        run: CI=true yarn test
        if: always()
